# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Administrator/Hoang_Design/Example/2.softcore/FFT_IP_Core-master/FFT_IP_Core-master/Design/IP_Core/FFT/FFT/FFT.xci
# IP: The module: 'FFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Hoang_Design/Example/2.softcore/FFT_IP_Core-master/FFT_IP_Core-master/Design/IP_Core/FFT/FFT/FFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Administrator/Hoang_Design/Example/2.softcore/FFT_IP_Core-master/FFT_IP_Core-master/Design/IP_Core/FFT/FFT/FFT.xci
# IP: The module: 'FFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Hoang_Design/Example/2.softcore/FFT_IP_Core-master/FFT_IP_Core-master/Design/IP_Core/FFT/FFT/FFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
